lightgbm:
  max_iter: 500
  learning_rate: 0.005
  max_depth: 5
  min_samples_leaf: 10
  random_state: 12345
logistic_regression:
  max_iter: 10000
  C: 1000
  random_state: 12345
random_forest:
  n_estimators: 500
  max_depth: 5
  min_samples_leaf: 10
  random_state: 12345
