lightgbm:
  n_estimators: 30
  learning_rate: 0.01
  max_depth: 5
  min_samples_leaf: 10
  random_state: 12345
logistic_regression:
  max_iter: 10000
  C: 100
  random_state: 12345
random_forest:
  n_estimators: 30
  max_depth: 5
  min_samples_leaf: 10
  random_state: 12345
